name: local_notifications_interface
description: A common platform interface for the flutter_local_notifications plugin.
version: 7.0.0+1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/local_notifications_interface

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
